// SPDX-License-Identifier: MIT
// Shared HTML-string helpers for every page builder. Hand-written template
// literals, no templating library or client-side framework — every page is
// plain, self-contained, static HTML (no external CDN, no build-time
// dependency the reader's browser needs to fetch), per the fully-static
// constraint in docs/decisions/mil-162-teachable-navigator.md.

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const STYLE = `
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; font-family: system-ui, -apple-system, "Segoe UI", sans-serif; line-height: 1.5;
    background: #fafafa; color: #1f2933;
  }
  header {
    padding: .75rem 1.25rem; background: #1f2933; color: #fff;
    display: flex; align-items: baseline; gap: .75rem; flex-wrap: wrap;
  }
  header a { color: #fff; text-decoration: none; font-weight: 600; }
  header .crumbs { color: #cbd2d9; font-size: 13px; }
  header .crumbs a { color: #cbd2d9; font-weight: 400; text-decoration: underline; }
  main { max-width: 1000px; margin: 0 auto; padding: 1.5rem 1.25rem 3rem; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { text-align: left; padding: .4rem .6rem; border-bottom: 1px solid #ddd; font-size: 14px; vertical-align: top; }
  th { font-weight: 600; background: #f0f2f5; }
  .badge { display: inline-block; padding: .1rem .5rem; border-radius: 999px; font-size: 12px; background: #e4e7eb; }
  .badge.ok { background: #d3f3df; color: #10633c; }
  .badge.warn { background: #fdecc8; color: #8a5a00; }
  .badge.bad { background: #fbdbd6; color: #9c2b1d; }
  .pattern { font-size: 12px; color: #52606d; }
  .stat-row { display: flex; flex-wrap: wrap; gap: .75rem; margin: 1rem 0 1.5rem; }
  .stat { background: #fff; border: 1px solid #ddd; border-radius: 8px; padding: .6rem .9rem; min-width: 9rem; }
  .stat .n { font-size: 1.4rem; font-weight: 700; display: block; }
  .stat .label { font-size: 12px; color: #52606d; }
  .diagram-frame {
    height: 420px; border: 1px solid #ddd; margin: 1rem 0; overflow: hidden; background: #fff;
    display: flex; align-items: flex-start; justify-content: center;
  }
  object.diagram { width: auto; height: 100%; max-width: 100%; }
  .full-diagram-link { margin: 0 0 1rem; font-size: 13px; }
  .doc { margin-top: 1.5rem; padding-top: 1rem; border-top: 1px solid #ddd; }
  .doc h1 { font-size: 1.3rem; }
  .doc h2 { font-size: 1.05rem; }
  .no-doc { color: #7b8794; font-style: italic; }
  .permalink { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; color: #52606d; }
  .permalink a { color: inherit; }
  code { background: #eee; padding: .05rem .3rem; border-radius: 3px; }
  footer { max-width: 1000px; margin: 0 auto; padding: 0 1.25rem 2rem; font-size: 12px; color: #7b8794; }
  .first-read-cta { display: inline-block; margin: .5rem 0 1rem; padding: .5rem 1rem; border-radius: 6px; background: #1f2933; color: #fff; text-decoration: none; font-weight: 600; }
`;

export interface Crumb {
  label: string;
  href: string;
}

/** `homeHref` is always relative to the page being built so the whole site
 *  works opened straight off disk via `file://` or served from any subpath —
 *  no absolute `href="/"` anywhere (that would jump to the filesystem/host
 *  root instead of the site root when the portal is published under a
 *  subpath, e.g. GitHub Pages project sites). */
export function layout(title: string, bodyHtml: string, homeHref: string, crumbs: Crumb[] = []): string {
  const crumbHtml = crumbs.length
    ? `<span class="crumbs">${crumbs.map((c) => `&rsaquo; <a href="${escapeHtml(c.href)}">${escapeHtml(c.label)}</a>`).join(" ")}</span>`
    : "";
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
  <style>${STYLE}</style>
</head>
<body>
  <header><a href="${escapeHtml(homeHref)}">em portal</a>${crumbHtml}</header>
  <main>
${bodyHtml}
  </main>
  <footer>Generated by em-portal — a static, read-only view over <code>em export</code>/<code>em status</code>. No server, no storage of its own; git is the source of truth.</footer>
</body>
</html>
`;
}
